### ISSUE TITLE
`java.lang.RuntimeException: All constructors on requested type must have a single parameter list` on case classes with defaults

### ISSUE THREAD

**Issue by s5bug** [liftmodules/json-extractor-ng#2]
Trying to `extractNg[Channel]` where Channel is

```
case class Channel(
                    id: Option[ULong] = None,
                    `type`: Option[Int] = None, // TODO make trait and serializer
                    guildId: Option[ULong] = None,
                    position: Option[Int] = None,
                    permissionOverwrites: Option[Array[JValue]] = None, // TODO make overwrites case class
                    name: Option[String] = None,
                    topic: Option[String] = None,
                    nsfw: Option[Boolean] = None,
                    lastMessageId: Option[ULong] = None,
                    bitrate: Option[Int] = None,
                    userLimit: Option[Int] = None,
                    recipients: Option[Array[User]] = None,
                    icon: Option[String] = None,
                    ownerId: Option[ULong] = None,
                    applicationId: Option[ULong] = None,
                    parentId: Option[ULong] = None,
                    lastPinTimestamp: Option[Instant] = None
                  )(implicit client: Client) extends Snowflaked {
```

fails with

```
Exception in thread "main" java.lang.RuntimeException: All constructors on requested type must have a single parameter list.
	at net.liftmodules.jsonextractorng.mapping.MappingMaker$.$anonfun$makeMapping$7(MappingMaker.scala:44)
	at scala.collection.immutable.List.map(List.scala:283)
	at net.liftmodules.jsonextractorng.mapping.MappingMaker$.makeMapping(MappingMaker.scala:42)
	at net.liftmodules.jsonextractorng.Extraction$ExtractionNg.extractNg(ExtractionNg.scala:14)
(my code stacktrace)
```

**Comment by farmdawgnation** [comment]
As I remarked in the thread on the Lift mailing list, this problem stems from having the `(implicit client: Client)` as a part of your constructor, which the default deserializers don't support.

Closing this as the library is actually working as expected - and is even giving a better error message than the default extractor library.
