### ISSUE TITLE
Serializers from Java based extractor that depend on non-JObject JValues fail to parse.

### ISSUE THREAD

**Issue by s5bug** [liftmodules/json-extractor-ng#3]
Given

    {
      "somethingIWantToParse": "1234"
    }

and

    case class IUseACustomDataType(
                                     somethingIWantToParse: SomethingWithACustom
                                  )

when there is a serializer like

    object SomethingWithACustomSerializer extends Serializer[SomethingWithACustom] {
    
      val somethingWithACustomClazz: Class[SomethingWithACustom] = classOf[SomethingWithACustom]
      
      override def deserialize(implicit format: Formats): PartialFunction[(TypeInfo, JValue), SomethingWithACustom] = {
        case (TypeInfo(`somethingWithACustomClazz`, _), json) => json match {
          case JString(s) => SomethingWithACustom(s)
          case x => throw new MappingException("Can't convert " + x + " to SomethingWithACustom")
        }
      }
    
      override def serialize(implicit format: Formats): PartialFunction[Any, JValue] = {
        case x: SomethingWithACustom => JString(x.toString)
      }
    }

in Formats, extractor-ng throws

    java.lang.Exception: Was expecting to see a JObject when building a SomethingWithACustom
	    at net.liftmodules.jsonextractorng.Extraction$ExtractionNg.executeMapping(ExtractionNg.scala:114)
	    at net.liftmodules.jsonextractorng.Extraction$ExtractionNg.executeMapping(ExtractionNg.scala:48)
	    at net.liftmodules.jsonextractorng.Extraction$ExtractionNg.$anonfun$executeMapping$7(ExtractionNg.scala:104)
	    at scala.collection.immutable.List.map(List.scala:283)
	    at net.liftmodules.jsonextractorng.Extraction$ExtractionNg.executeMapping(ExtractionNg.scala:102)
	    at net.liftmodules.jsonextractorng.Extraction$ExtractionNg.extractNg(ExtractionNg.scala:15)

when trying to parse JSON.

**Comment by farmdawgnation** [comment]
< headscratch >

I know why that is and I guess I didn't think that would be a sensible thing to do. But! Guess I'm wrong. :D
